# Generated by Django 4.2.1 on 2023-05-16 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerships', '0001_initial'),
        ('cars', '0002_car_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dearlership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealerships.dealerships'),
        ),
    ]
